### ISSUE TITLE
Dataset to be considered: AsyLex

### ISSUE THREAD

**Issue by JulienGaumez** [JoelNiklaus/LawInstruct#13]
AsyLex introduces 59,112 documents of refugee status determination in Canada from 1996 to 2022, providing researchers and practitioners with essential material for training and evaluating NLP models for legal research and case review. AsyLex includes gold-standard human-labeled annotations for 24 legally relevant entity types curated with the help of legal experts, and 1,682 gold-standard labeled documents for the outcome of the case.

Dataset: https://huggingface.co/datasets/clairebarale/AsyLex

**Comment by JoelNiklaus** [comment]
Is the data public? Could you provide a link?

**Comment by JulienGaumez** [comment]
I had a further look into this dataset trying to implement it. The structure of the data is quite unclear and 5 out of the 7 subsets are not directly accessible through HF as they raise some error. (One can still download the files though.) The labeled outcomes are given with just a decisionID that represents the ending of the filename of the downloadable cases_anonymised_raw_text folder that contains 59'000 txt files. Additionally the raw text files mostly contain a clear statement of the case at the end of the file anyway. Making the task of predicting the outcome of said case quite trivial. 
 
 Example of such a clear statement:
 Kosovo.   Accordingly, the claimant is neither a Convention refugee nor a person in need of 
protection.  
[42]  The claim is rejected.  
 
 Is it actually worth for me to go trough the effort of trying to put the data into a more usable form or should I abort this dataset?

**Comment by JoelNiklaus** [comment]
Thanks for the explanation. No, I think you are right. Let's disregard it for now. Can you please add this dataset [here](https://github.com/JoelNiklaus/LawInstruct?tab=readme-ov-file#other-datasets) with a quick explanation and a link to this issue?
