### ISSUE TITLE
Dataset to be considered: StaRD

### ISSUE THREAD

**Issue by JulienGaumez** [JoelNiklaus/LawInstruct#17]
STARD is derived from real-world legal consultation questions made by the general public.
Unlike existing statute retrieval datasets that focus predominantly on professional legal queries, STARD captures the complexity and diversity of layperson queries.

Dataset: https://github.com/oneal2000/STARD/tree/main

**Comment by JoelNiklaus** [comment]
This is also a Chinese dataset, disregarding for now because not our focus.
